api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "price-override-function"
type = "function"
uid = "768cf5a6-bd74-a16c-0c9f-7aabd8752c10121dff15"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
